---
language: python
python: "2.7"
sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1
  - ANSIBLE_CONFIG=tests/ansible.cfg

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

before_script:
  # Run testing setup
  - tests/setup.sh

script:
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence: PASS' && exit 0)
    || (echo 'Idempotence: FAIL' && exit 1)

notifications:
  email: true
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

